### ISSUE TITLE
App and website: Trips dates incorrect.

### ISSUE THREAD

**Issue by Romkabouter** [recom3/api-hud-goggle#5]
Hi there, 

During my latest trip I have tracked some runs.
The app shows incorrect data. The trip was in Austria and on separate days. It also show 1 run, which is not correct.

![Screenshot_20230220-103827](https://user-images.githubusercontent.com/4774478/220082603-65e74993-0e21-4f4e-af50-f26c78763e58.png)

The website shows the tracks in the correct position, but dates are incorrect.
<img width="698" alt="image" src="https://user-images.githubusercontent.com/4774478/220083130-d91c365a-6ede-4a1e-9560-2fb13ff7f33d.png">

When I use the RIB to gpx exporter, I can see a timestamp per trackpoint:
<img width="391" alt="image" src="https://user-images.githubusercontent.com/4774478/220086129-4f4e489c-82ca-41e2-a603-7c9335dec11b.png">

I think it is save to assume that the first trackpoint can be used to extract the location and date metadata.

Is the app a complete rewrite of the original Engage App?

**Comment by recom3** [comment]
Good day
Let us check. Yes maybe the country is wrong as the main focus was to extract correct data of elevation, gps data, etc.
The time we will check too.
This Uplink Desktop is complete new.
Regards.

**Comment by recom3** [comment]
Ok we will fix it and there will be also a mechanism to fix the already uploaded trips.

**Comment by recom3** [comment]
Working in the fix.
We have to update a little the current api, but will be ready soon.
We will use this time to update the Uplink Desktop feed-back too.

**Comment by recom3** [comment]
Fix deployed for Country to API

**Comment by recom3** [comment]
Fix deployed to Uplink Desktop app.
For existing trips we will leave them as they are, possibly correct country with one shop update.
From now on should be correct.

**Comment by Romkabouter** [comment]
> Fix deployed for Country to API

Should I redownload and install the app?

**Comment by recom3** [comment]
No the phone App is OK is taking data from the api, should be ok.
You need to download the Uplink Desktop to be able to upload corrected data (new trips).

**Comment by Romkabouter** [comment]
OK, I'll check it!

**Comment by recom3** [comment]
We have included the country in the Web too.
![image](https://user-images.githubusercontent.com/102611090/224148118-52e36926-2931-4941-91bc-f5299c38933e.png)

**Comment by Romkabouter** [comment]
> You need to download the Uplink Desktop to be able to upload corrected data (new trips).

I have downloaded a new version and then uploaded new tracks.
Two issue
- tracks are double (1 with correct country Germany)
- Dates still incorrect, I have uploaded them today (13-03), but the trips were 11-03 and 12-03

<img width="734" alt="image" src="https://user-images.githubusercontent.com/4774478/224819534-94968868-5e91-4f72-a923-662990b98a32.png">

**Comment by recom3** [comment]
Ok thx we will check

**Comment by recom3** [comment]
They are not repeated.
Probably there is a small bug in Uplink Desktop that prevents obtaining the datetime from tracks format 1 (probably you have and updated Snow2, not the factory one, that uses format 2 - Transcend)
Then when uploading the trip the program asigns:
Trip yyyy-MM-dd HH:mm
Should be maybe Trip yyyy-MM-dd HH:mm:ss, when is impossible to obtain the datetime  from track.
We will fix in any case.
Many thx!

**Comment by Romkabouter** [comment]
> robably you have and updated Snow2, not the factory one, that uses format 2 - Transcend

My Snow2 is on the latest ReconOS4, I believe the version before that was 3.2.1

**Comment by recom3** [comment]
Fixed with new version of Uplink Desktop.
Now datetime should be correct.
In any case, in future, in web site will be possible to edit trip names to put with more meaning for the user.
Thx for the feed back.

**Comment by recom3** [comment]
I think that can be done.
From which track/track id do you want to delete?

**Comment by Romkabouter** [comment]
You can delete all of them, wo whenI synch the Snow2 they should all popup again right?

**Comment by Romkabouter** [comment]
Sorry guys, but this is not fixed.
I did update the MaxRib with zero, but now the trips have several issues:

- dates are not from the trip, but the upload date
- all trips are the same on the map
- multiple duplicates

I have no issues with you deleting my data and to try it again if that helps.

> Search for this in the file with text editor (I assume your unit id is 283332129):

This might be a cause: I actually have two devices {"Id":"283332129","MaxRib":352},{"Id":"291952246","MaxRib":0}]

**Comment by recom3** [comment]
This is normal you have two devices.
Have you downloaded the last version of the Uplink Desktop?
If not, we will delete the trips again no problem. You can download again de Uplink and re-try.

**Comment by recom3** [comment]
Trips deleted again.

**Comment by Romkabouter** [comment]
Thanks, I have used this version:
<img width="774" alt="image" src="https://user-images.githubusercontent.com/4774478/227459058-76f37c8c-f32d-4f20-b158-7f07a70e2384.png">

I have set the MaxRib to 0, but also deleted the RIB files (also ID.RIB) on AppData\Local\Recon Instruments\

Same result, the name is the upload date, while I expect the tripdate.
Country is correct, but there are too many trips
Also, all trips are the same track. The first track.
<img width="684" alt="image" src="https://user-images.githubusercontent.com/4774478/227460811-299e7cb7-50ed-416f-b800-0718c08918a5.png">

My expectations is 1 entry per day, which can be a combination of multible rib files.
For the moment I a fine with 1 entry per RIB file, but this upload seems to have a lot of issues.

**Comment by recom3** [comment]
Ok we will double check. Maybe the release not correctly pushed to server and is old.
In new version trips should be at least ...hh:mm:ss...
Sorry for that

**Comment by Romkabouter** [comment]
No problems, happy to help :)

**Comment by recom3** [comment]
We are going to double check the code and produce a new version in the exe so can be easily checked.

**Comment by recom3** [comment]
Maybe the RIB format in your version is somehow different. Could you please upload one.

**Comment by Romkabouter** [comment]
Sure, the are in https://romkabouter.stackstorage.com/s/lmwQDS1MpVZqp9eR (RIB folder)
I have uploaded 3, also the generate gpx file from 300.
When I check that, the data look find to me (lat/lon/speed/date etc) so I think the uplink is generating the gpx ok.

The graph look good as well
![image](https://user-images.githubusercontent.com/4774478/227730039-0a5c445b-554c-4121-966c-9e42b51433f6.png)

Was there a good as to why this conversion is done locally and not on the server? The RIB files are much smaller to upload. I think the issue is on the server and not in the uplink

**Comment by Romkabouter** [comment]
I you can delete my data again, I will remove my local (test) track from the device and only upload the real trips.
Also, it would be a good reference on the site of the RIB number was visible, that way I could check if it is correct

**Comment by Romkabouter** [comment]
Hmm. I see a lot of RIB files on there which is not a day. It looks like the device is also creating RIB files when not actually tracking (Start Day), but always when GPS is on. I am gonna look into that. That would be a reason for all the tracks in NL, because the device is sitting on my desk.

**Comment by Romkabouter** [comment]
> Might be caused by the fact I have the setting GPS Always on to true.

100% that is the issue here. When GPS is always on, the Snow2 generates RIB files even if there is no activity being tracked.
When it is off, no RIB files are generated. So maybe there is some trick with EVENTxxx.RIB, cannot tell

**Comment by recom3** [comment]
I think a silly bug in in the code producing the trip name...
We will produce the version 1.1 and be back.

**Comment by recom3** [comment]
Trips deleted and new version of Uplink uploaded again
When you download, please click in the exe and check is 1.1 like this:
![image](https://user-images.githubusercontent.com/102611090/227798245-ee6f92a0-658f-4372-9a02-a8fb0ea19a61.png)

**Comment by Romkabouter** [comment]
Used this version:

<img width="357" alt="image" src="https://user-images.githubusercontent.com/4774478/227804746-4b387874-ea92-4641-82a8-191c25df3f99.png">

Same issues, names are upload date and it looks like last trip is copied to all other trips. 

<img width="1150" alt="image" src="https://user-images.githubusercontent.com/4774478/227805033-5298fc8e-504b-4dd3-87fa-cdd425ef984c.png">

**Comment by recom3** [comment]
Mm it is very strange. We have tested your RIBs and working fine, must something else.
We will check other modules, maybe is not in the decoder.

**Comment by recom3** [comment]
Good day,
Should be fixed.
We have found another small bug in Uplink, so we have released the 1.1.0.1 (plz download it)
and also we fixed the API.

**Comment by Romkabouter** [comment]
> Sorry. We forgot to delete your tracks, shall we do it, so you can retry?

Yeah sure :)

> The device can store a lot of RIB's sometimes. You can check, if it anything meaningful with the file size.
> There is a cap in file size, below which trip is not uploaded.

I have removed all nonsens trips. The filesize of DAY287 is 440kb and not uploaded.
The filesize of DAY336 is 322KB and ís uploaded. 
So if there is a cap, which makes sense I guess, there is something out of order there.

My smallest file is DAY295.RIB, but still a valid track. A short one, probably the battery was dead
<img width="1378" alt="image" src="https://user-images.githubusercontent.com/4774478/228075434-d0829fd5-4954-4390-992a-3677fdcd04f9.png">

**Comment by recom3** [comment]
Deleted
The cap is small 10000 bytes

**Comment by Romkabouter** [comment]
I have used 1.1.0.1 but that does not seems to have any effect? Should there have been a new version?

**Comment by recom3** [comment]
1.1.0.1 is the last version yes. There was an issue in the API with the naming that was corrected yesterday.
How many Trips were uploaded? Was the naming OK?

**Comment by recom3** [comment]
Was the maxrib updated in the prefs json file?

**Comment by Romkabouter** [comment]
Yes, otherwise the trips would not have been uploaded at all I assume

**Comment by recom3** [comment]
So only 4 trips appearing in the grid below the map right?

**Comment by recom3** [comment]
Ok we check.
Click in the Track id to render, in the grid. We see an issue here.

**Comment by Romkabouter** [comment]
> We see in DB trips from 136 to 139 including both.

Sorry, I do not understand. Trips 136 to 139 are correct dates and Country.
I am missing older trips, from the same device. You can see the RIB names in a screenshot in earlier comments.
They are all my Snow2 device. (I have other devices but not synchronising those)

**Comment by Romkabouter** [comment]
Yes, also 300 and 302

**Comment by recom3** [comment]
Are the gpx files in the C:\Users\<user_name>\AppData\Local\Recon Instruments
I mean, before uploading them, they are converted. So the point failing is maybe in the upload.

**Comment by Romkabouter** [comment]
> Are the gpx files in the C:\Users<user_name>\AppData\Local\Recon Instruments I mean, before uploading them, they are converted. So the point failing is maybe in the upload.

No they are not, only the gpx and rib files as I posted before:

![image](https://user-images.githubusercontent.com/4774478/228354996-8611d795-1c40-4f47-9ce7-f8ae83fe04d4.png)

The rest is missing on the pc and on the site

**Comment by recom3** [comment]
Ok, so they are stuck in the step from device to PC. I assume you can copy the using Windows Explorer from device.

**Comment by Romkabouter** [comment]
Obviously yes, but I expect the Uplink tool to do that for me. Like the 4 that are correctly done at the moment.
But the tool does not copy all RIB files from the device, even if I set the MaxRib to 0.

**Comment by recom3** [comment]
Ok we will include some logs. What is strange is that now the converter with country and datetime works fine, this that worked before and is simpler, now fails...
So is life!

**Comment by recom3** [comment]
Hello,
We have produce the new version of Uplink 1.1.0.2 with a small log (please download it).
Trips have been deleted from DB too.
Please remove before sync any RIB,GPX from (...)\AppData\Local\Recon Instruments directory (just in case)
After sync in recom3.log file, something like this would be expected:
![image](https://user-images.githubusercontent.com/102611090/228786259-acf9fac2-4761-4cda-ad13-73a307943495.png)

**Comment by Romkabouter** [comment]
Hi there. I have remove all files from Appdata and resynched. This is the log

<img width="724" alt="image" src="https://user-images.githubusercontent.com/4774478/229049920-aa3f2b72-86a7-45c2-95d1-0dcfe880ded6.png">

However, again not downloading all files. This is the Tripdata folder on the device
<img width="824" alt="image" src="https://user-images.githubusercontent.com/4774478/229050655-5b542d29-ba7d-4231-86cd-6a1957409783.png">

And again, website is not fixed. Same tracks regardless of clicking different grid entries.
Date and country still correct.

**Comment by recom3** [comment]
Ok thx for the feedback! Still not clear why is not detecting the others in the device (maybe hidden Exception).
We will enrich further the logs to find out.
About the Web grid, have you tried clicking in the id?
![image](https://user-images.githubusercontent.com/102611090/229144849-f26f5d83-b07c-4c76-a203-a85dca2a2bab.png)

**Comment by Romkabouter** [comment]
Ah ok! No I just clicked somewhere in the row. Clicking the id works :)
If I can help with providing logs or anything, no problems. I do not mind resetting and resynching my Snow2

**Comment by Romkabouter** [comment]
Should we create a separate issue for that? Because the other issue is fixed, apart from the fact you have to click the ID

**Comment by recom3** [comment]
Hello,
Yes, please create an issue for the grid thing. Clicking in the row can be somehow confusing.
In the mean time, we think have found the bug while enriching the logs (really silly bug indeed).
We have deleted your trips and produce a new version 1.1.0.3
Could you please download it, try again and in case does not work paste the logs, that now have more info.
Thx.

**Comment by Romkabouter** [comment]
> Could you please download it, try again and in case does not work paste the logs, that now have more info.
> Thx.

I have resynched the goggle, it seems to me that all is working as expected now.  Good work. I see one RIB not beïng uploaden, but that is probably because is is very small  and not a real track.

<img width="1042" alt="Schermafbeelding 2023-03-31 om 20 09 41" src="https://user-images.githubusercontent.com/4774478/229272214-3e1fe0b6-f169-42ff-839d-6f4e79ddd01d.png">

There are also the EVENT.rib files, do you guys have any idea as to what they are for? I will create another issue for the grid thing.

**Comment by recom3** [comment]
Thx to you for your help!
Not a clue about the EVENT ones. Seems very small.

**Comment by Romkabouter** [comment]
I have some contact with the original dev's I'll see if I can get some more info
